# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDD9YIrSgpCET0t40jqffAurkTeumeEF
"""

while True:
  try:
    nota =  int(input('De 0 a 100 como você avalia esse atendimento?  '))
  except ValueError:
    print('Entrada inválida. Digite um valor inteiro')
  else:
    if (nota > 100) or (nota < 0):
      print('Entrada fora do intervelo. Digite um número inteiro entre 0 e 100')
      print('Por exemplo: 100')
    else:
      if nota >= 90:
        print('Atendimento de qualidade')
      elif nota >= 70 and nota <=89:
        print('Atendimento neutro')
      elif nota <= 69:
        print('Atendimento insatisfatório')
      break

