-- Remoção da Tabela Fato
DROP TABLE FTO_MC_CD_NOTAS CASCADE CONSTRAINTS;

-- Remoção das Dimensões Relacionadas à Fato
DROP TABLE DIM_MC_CENTRO_DIST CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_ENTREGADOR CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_CD_TEMPO CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_PRODUTO CASCADE CONSTRAINTS;

-- Remoção das Dimensões Snowflake (Produto)
DROP TABLE DIM_MC_SUBCATEGORIA CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_CATEGORIA CASCADE CONSTRAINTS;

-- Remoção das Dimensões Snowflake (Localização)
DROP TABLE DIM_MC_LOCALIZACAO CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_BAIRRO CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_CIDADE CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_ESTADO CASCADE CONSTRAINTS;
DROP TABLE DIM_MC_REGIAO CASCADE CONSTRAINTS;
