-- Tabela de Região 
CREATE TABLE DIM_MC_REGIAO (
    ID_REGIAO NUMBER(10) NOT NULL,
    NOME_REGIAO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_DIM_MC_REGIAO PRIMARY KEY (ID_REGIAO)
);

-- Tabela de Estado
CREATE TABLE DIM_MC_ESTADO (
    ID_ESTADO NUMBER(10) NOT NULL,
    ID_REGIAO NUMBER(10) NOT NULL,
    SIGLA_ESTADO VARCHAR2(2) NOT NULL,
    NOME_ESTADO VARCHAR2(50) NOT NULL,
    GENTILICO VARCHAR2(50),
    CONSTRAINT PK_DIM_MC_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT FK_ESTADO_REGIAO FOREIGN KEY (ID_REGIAO) REFERENCES DIM_MC_REGIAO(ID_REGIAO)
);

-- Tabela de Cidade 
CREATE TABLE DIM_MC_CIDADE (
    ID_CIDADE NUMBER(10) NOT NULL,
    ID_ESTADO NUMBER(10) NOT NULL,
    NOME_CIDADE VARCHAR2(100) NOT NULL,
    NR_POPULACAO VARCHAR2(20),
    CODIGO_IBGE VARCHAR2(10),
    ALTITUDE NUMBER(10),
    CONSTRAINT PK_DIM_MC_CIDADE PRIMARY KEY (ID_CIDADE),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES DIM_MC_ESTADO(ID_ESTADO)
);

-- Tabela de Bairro 
CREATE TABLE DIM_MC_BAIRRO (
    ID_BAIRRO NUMBER(10) NOT NULL,
    ID_CIDADE NUMBER(10) NOT NULL,
    NOME_BAIRRO VARCHAR2(100) NOT NULL,
    NR_POPULACAO_BAIRRO VARCHAR2(20),
    NR_NIVEL_SEGURANCA NUMBER(2),
    CONSTRAINT PK_DIM_MC_BAIRRO PRIMARY KEY (ID_BAIRRO),
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES DIM_MC_CIDADE(ID_CIDADE)
);

-- Tabela de logradouro 
CREATE TABLE DIM_MC_LOCALIZACAO (
    ID_LOCALIZACAO NUMBER(10) NOT NULL,
    ID_BAIRRO NUMBER(10) NOT NULL,
    NOME_LOGRADOURO VARCHAR2(150),
    NR_LOGRADOURO VARCHAR2(20),
    NR_CEP VARCHAR2(20),
    CONSTRAINT PK_DIM_MC_LOCALIZACAO PRIMARY KEY (ID_LOCALIZACAO),
    CONSTRAINT FK_LOCAL_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES DIM_MC_BAIRRO(ID_BAIRRO)
);

-- Tabela de Categoria 
CREATE TABLE DIM_MC_CATEGORIA (
    ID_CATEGORIA NUMBER(10) NOT NULL,
    NOME_CATEGORIA VARCHAR2(100) NOT NULL,
    ST_CATEGORIA VARCHAR2(5),
    NR_AVALIACAO_CATEGORIA NUMBER(3,1),
    CONSTRAINT PK_DIM_MC_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

-- Tabela de Subcategoria 
CREATE TABLE DIM_MC_SUBCATEGORIA (
    ID_SUBCATEGORIA NUMBER(10) NOT NULL,
    ID_CATEGORIA NUMBER(10) NOT NULL,
    NOME_SUBCATEGORIA VARCHAR2(100) NOT NULL,
    ST_SUB_CATEGORIA VARCHAR2(5),
    NR_AVALIACAO_SUB_CATEGORIA NUMBER(3,1),
    CONSTRAINT PK_DIM_MC_SUBCATEGORIA PRIMARY KEY (ID_SUBCATEGORIA),
    CONSTRAINT FK_SUBCAT_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES DIM_MC_CATEGORIA(ID_CATEGORIA)
);

-- Tabela de Produto Base
CREATE TABLE DIM_MC_PRODUTO (
    ID_PRODUTO NUMBER(10) NOT NULL,
    ID_SUBCATEGORIA NUMBER(10) NOT NULL,
    NOME_PRODUTO VARCHAR2(150) NOT NULL,
    EMBALAGEM VARCHAR2(50),
    VL_UNITARIO NUMBER(10,2),
    PERC_ICMS VARCHAR2(10),
    CONSTRAINT PK_DIM_MC_PRODUTO PRIMARY KEY (ID_PRODUTO),
    CONSTRAINT FK_PROD_SUBCAT FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES DIM_MC_SUBCATEGORIA(ID_SUBCATEGORIA)
);

-- Tabela de Tempo
CREATE TABLE DIM_MC_CD_TEMPO (
    ID_TEMPO NUMBER(10) NOT NULL,
    DATA_COMPLETA DATE NOT NULL,
    NR_DIA NUMBER(2),
    NR_MES NUMBER(2),
    NR_ANO NUMBER(4),
    CONSTRAINT PK_DIM_MC_CD_TEMPO PRIMARY KEY (ID_TEMPO)
);

-- Tabela de Cliente
CREATE TABLE DIM_MC_CLIENTE (
    NR_CLIENTE NUMBER(10) NOT NULL,
    ID_LOCALIZACAO NUMBER(10) NOT NULL,
    NOME_CLIENTE VARCHAR2(150),
    NR_ESTRELAS NUMBER(2),
    ST_CLIENTE VARCHAR2(5),
    DT_NASCIMENTO DATE,
    CONSTRAINT PK_DIM_MC_CLIENTE PRIMARY KEY (NR_CLIENTE),
    CONSTRAINT FK_CLIENTE_LOCAL FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_MC_LOCALIZACAO(ID_LOCALIZACAO)
);

-- Tabela de Centro de Distribuição
CREATE TABLE DIM_MC_CENTRO_DIST (
    ID_CD NUMBER(10) NOT NULL,
    ID_LOCALIZACAO NUMBER(10) NOT NULL,
    CD_CD VARCHAR2(50),
    NOME_CENTRO_DISTRIBUICAO VARCHAR2(150),
    CONSTRAINT PK_DIM_MC_CENTRO_DIST PRIMARY KEY (ID_CD),
    CONSTRAINT FK_CD_LOCAL FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_MC_LOCALIZACAO(ID_LOCALIZACAO)
);

-- Tabela de Entregador
CREATE TABLE DIM_MC_ENTREGADOR (
    ID_ENTREGADOR NUMBER(10) NOT NULL,
    NOME_ENTREGADOR VARCHAR2(150),
    CONSTRAINT PK_DIM_MC_ENTREGADOR PRIMARY KEY (ID_ENTREGADOR)
);

-- Tabela Fato 
CREATE TABLE FTO_MC_CD_NOTAS (
    NR_PEDIDO NUMBER(15) NOT NULL,
    NR_ITEM NUMBER(10) NOT NULL,
    NR_CLIENTE NUMBER(10) NOT NULL,
    ID_CD NUMBER(10) NOT NULL,
    ID_PRODUTO NUMBER(10) NOT NULL,
    ID_ENTREGADOR NUMBER(10) NOT NULL,
    ID_TEMPO_PEDIDO NUMBER(10) NOT NULL,
    ID_TEMPO_PREVISTA NUMBER(10) NOT NULL,
    ID_TEMPO_ENTREGA NUMBER(10) NOT NULL,
    QUANTIDADE NUMBER(10),
    VL_TOTAL NUMBER(10,2),
    QT_PROD_ENTREGUE NUMBER(10),
    NOTA_EMBALAGEM NUMBER(4,2),
    NOTA_PONTUALIDADE NUMBER(4,2),
    NOTA_CORTESIA NUMBER(4,2),
    CONSTRAINT PK_FTO_MC_CD_NOTAS PRIMARY KEY (NR_PEDIDO, NR_ITEM),
    CONSTRAINT FK_FTO_CLIENTE FOREIGN KEY (NR_CLIENTE) REFERENCES DIM_MC_CLIENTE(NR_CLIENTE),
    CONSTRAINT FK_FTO_CD FOREIGN KEY (ID_CD) REFERENCES DIM_MC_CENTRO_DIST(ID_CD),
    CONSTRAINT FK_FTO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_MC_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_FTO_ENTREGADOR FOREIGN KEY (ID_ENTREGADOR) REFERENCES DIM_MC_ENTREGADOR(ID_ENTREGADOR),
    CONSTRAINT FK_FTO_TEMPO_PEDIDO FOREIGN KEY (ID_TEMPO_PEDIDO) REFERENCES DIM_MC_CD_TEMPO(ID_TEMPO),
    CONSTRAINT FK_FTO_TEMPO_PREVISTA FOREIGN KEY (ID_TEMPO_PREVISTA) REFERENCES DIM_MC_CD_TEMPO(ID_TEMPO),
    CONSTRAINT FK_FTO_TEMPO_ENTREGA FOREIGN KEY (ID_TEMPO_ENTREGA) REFERENCES DIM_MC_CD_TEMPO(ID_TEMPO)
);
