-- Desafio 1

-- Item A:


set serveroutput on;
DECLARE
V_NR_SAC MC_SGV_SAC.NR_SAC%TYPE;
V_DT_ABERTURA_SAC MC_SGV_SAC.DT_ABERTURA_SAC%TYPE;
V_HR_ABERTURA_SAC MC_SGV_SAC.HR_ABERTURA_SAC%TYPE;
V_TP_SAC MC_SGV_SAC.TP_SAC%TYPE; -- Item que será transformado

V_CD_PRODUTO MC_PRODUTO.CD_PRODUTO%TYPE;
V_DS_PRODUTO MC_PRODUTO.DS_PRODUTO%TYPE;
V_VL_UNITARIO MC_PRODUTO.VL_UNITARIO%TYPE;
V_VL_PERC_LUCRO MC_PRODUTO.VL_PERC_LUCRO%TYPE;

V_NR_CLIENTE MC_CLIENTE.NR_CLIENTE%TYPE;
V_NM_CLIENTE MC_CLIENTE.NM_CLIENTE%TYPE;

V_SG_ESTADO MC_ESTADO.SG_ESTADO%TYPE;
V_NM_ESTADO MC_ESTADO.NM_ESTADO%TYPE;

V_DS_TIPO_CLASSIFICACAO_SAC MC_SGV_OCORRENCIA_SAC.DS_TIPO_CLASSIFICACAO_SAC%TYPE;

CURSOR cFINAL IS 
SELECT S.NR_SAC, S.DT_ABERTURA_SAC, S.HR_ABERTURA_SAC, S.TP_SAC, P.CD_PRODUTO,
P.DS_PRODUTO,P.VL_UNITARIO, P.VL_PERC_LUCRO, C.NR_CLIENTE, C.NM_CLIENTE, E.SG_ESTADO,
E.NM_ESTADO
FROM MC_CLIENTE C INNER JOIN MC_SGV_SAC S 
ON (C.NR_CLIENTE = S.NR_CLIENTE)
INNER JOIN MC_PRODUTO P 
ON (S.CD_PRODUTO = P.CD_PRODUTO)
INNER JOIN (SELECT  ES.SG_ESTADO, ES.NM_ESTADO, EN.NR_CLIENTE
                              FROM  MC_END_CLI EN INNER JOIN  MC_LOGRADOURO LG
                              ON(EN.CD_LOGRADOURO_CLI = LG.CD_LOGRADOURO)
                              INNER JOIN MC_BAIRRO BA
                              ON(LG.CD_BAIRRO = BA.CD_BAIRRO)
                              INNER JOIN MC_CIDADE CI
                              ON(BA.CD_CIDADE = CI.CD_CIDADE)
                              INNER JOIN MC_ESTADO ES
                              ON(CI.SG_ESTADO = ES.SG_ESTADO)
                          )E
ON(S.NR_CLIENTE = E.NR_CLIENTE);
BEGIN
-- ITEM A: CURSOR (exibindo itens)
OPEN cFINAL;

LOOP
FETCH cFINAL INTO V_NR_SAC, V_DT_ABERTURA_SAC, V_HR_ABERTURA_SAC, V_TP_SAC,
V_CD_PRODUTO, V_DS_PRODUTO, V_VL_UNITARIO, V_VL_PERC_LUCRO, V_NR_CLIENTE, 
V_NM_CLIENTE, V_SG_ESTADO, V_NM_ESTADO;

dbms_output.put_line('o número sac: ' || V_NR_SAC || 
' com data de abertura em: ' ||V_DT_ABERTURA_SAC||
' no horário: ' ||V_HR_ABERTURA_SAC|| 
' com tipo de sac: ' ||V_TP_SAC||
' cd_produto: '||V_CD_PRODUTO||
' ds_Produto: ' ||V_DS_PRODUTO||
' vl_unitario: '||V_VL_UNITARIO||
' vl_perc_lucro: ' ||V_VL_PERC_LUCRO||
' nr_cliente: ' ||V_NR_CLIENTE|| 
' nm_cliente: ' ||V_NM_CLIENTE||
' sg_estado: '||V_SG_ESTADO||
' nm_estado: '||V_NM_ESTADO);
IF cFINAL%NOTFOUND THEN
    EXIT;
    END IF;
END LOOP;
CLOSE cFINAL;

dbms_output.put_line('');

-- ITEM B
OPEN cFINAL;

LOOP
FETCH cFINAL INTO V_NR_SAC, V_DT_ABERTURA_SAC, V_HR_ABERTURA_SAC, V_TP_SAC,
V_CD_PRODUTO, V_DS_PRODUTO, V_VL_UNITARIO, V_VL_PERC_LUCRO, V_NR_CLIENTE, 
V_NM_CLIENTE, V_SG_ESTADO, V_NM_ESTADO;

dbms_output.put_line('o número sac: ' || V_NR_SAC || 
' com data de abertura em: ' ||V_DT_ABERTURA_SAC||
' no horário: ' ||V_HR_ABERTURA_SAC|| 
' com tipo de sac: ' ||V_TP_SAC||
' cd_produto: '||V_CD_PRODUTO||
' ds_Produto: ' ||V_DS_PRODUTO||
' vl_unitario: '||V_VL_UNITARIO||
' vl_perc_lucro: ' ||V_VL_PERC_LUCRO||
' nr_cliente: ' ||V_NR_CLIENTE|| 
' nm_cliente: ' ||V_NM_CLIENTE||
' sg_estado: '||V_SG_ESTADO||
' nm_estado: '||V_NM_ESTADO);
IF cFINAL%NOTFOUND THEN
    EXIT;
END IF;
    -- ITEM B.1: 
-- Coluna TP_SAC = CHAR(1) - armazena S, E, D.
-- Coluna DS_TIPO_CLASSIFICACAO_SAC - Armazena a descrição do tipo definido em TP_SAC.
    
IF V_TP_SAC = 'S' THEN
V_DS_TIPO_CLASSIFICACAO_SAC := 'Sugestão';
ELSIF V_TP_SAC = 'E' THEN
V_DS_TIPO_CLASSIFICACAO_SAC := 'Elogio';
ELSIF V_TP_SAC = 'D' THEN
V_DS_TIPO_CLASSIFICACAO_SAC := 'Dúvida';
ELSE
dbms_output.put_line('Classificação inválida');
END IF;

INSERT INTO MC_SGV_OCORRENCIA_SAC -- ITEM B.4
VALUES (
    V_NR_SAC,
    V_DT_ABERTURA_SAC,
    V_HR_ABERTURA_SAC,
    V_DS_TIPO_CLASSIFICACAO_SAC , -- ITEM B.1
    V_CD_PRODUTO,
    V_DS_PRODUTO,
    V_VL_UNITARIO,
    V_VL_PERC_LUCRO,
    (V_VL_PERC_LUCRO/100)*V_VL_UNITARIO, --ITEM B.2:
    V_SG_ESTADO,
    V_NM_ESTADO,
    V_NR_CLIENTE,
    V_NM_CLIENTE,
    NULL -- ITEM B.3
    );
    
END LOOP;
CLOSE cFINAL;
END;

COMMIT; -- ITEM B.5






-- DESAFIO 2:

--ITEM A:

SELECT CP.CD_CATEGORIA,CP.TP_CATEGORIA,CP.DS_CATEGORIA,CP.DT_INICIO,CP.DT_TERMINO,CP.ST_CATEGORIA, 
COUNT(SAC.NR_SAC) AS TOTAL_CHAMADOS
FROM MC_CATEGORIA_PROD CP LEFT JOIN MC_PRODUTO PRO
    ON CP.CD_CATEGORIA = PRO.CD_CATEGORIA 
    LEFT JOIN MC_SGV_SAC SAC
    ON PRO.CD_PRODUTO = SAC.CD_PRODUTO
GROUP BY CP.CD_CATEGORIA,CP.TP_CATEGORIA,CP.DS_CATEGORIA,CP.DT_INICIO, CP.DT_TERMINO, CP.ST_CATEGORIA
ORDER BY CD_CATEGORIA;

    