-- =============================================================================
-- PROJETO DATA MART ESTOQUE - MELHORES COMPRAS
-- SCRIPT DE REMOÇÃO DO MODELO DIMENSIONAL
-- ARQUIVO: apaga.sql
-- =============================================================================

-- 1. REMOÇÃO DA TABELA FATO (Contém as Chaves Estrangeiras)
DROP TABLE FATO_ESTOQUE CASCADE CONSTRAINTS;

-- 2. REMOÇÃO DAS TABELAS DE DIMENSÃO
DROP TABLE DIM_PROMOCAO CASCADE CONSTRAINTS;
DROP TABLE DIM_CENTRO_DISTRIBUICAO CASCADE CONSTRAINTS;
DROP TABLE DIM_FORNECEDOR CASCADE CONSTRAINTS;
DROP TABLE DIM_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS;
